/* Контент чата для виджета — генерируется вместе с api/_chat-content.js */
window.NIGUMA_CHAT = {
  "ru": {
    "answers": {
      "greeting": "Здравствуйте! Это чат 15minYoga. Спросите о расписании, стоимости или самой практике — отвечу здесь, а если понадобится, передам вопрос человеку.",
      "price": "Участие стоит: 1 месяц — 100 €, 6 месяцев — 500 €, 12 месяцев — 900 €. Реквизиты для оплаты бот в Telegram присылает лично.",
      "schedule": "Живые практики идут с понедельника по пятницу, 07:00–07:15 по венскому времени (GMT+2). По субботам — более длинная встреча с разбором техники и ответами на вопросы. Если пропустили — записи всех практик доступны участникам.",
      "included": "В участие входят ежедневные живые практики, субботняя встреча с разбором техники, записи всех занятий и закрытое сообщество в Telegram. Там же — поддержка и общение с другими предпринимателями и руководителями.",
      "payment": "Оплатить можно четырьмя способами: PayPal, счёт на банковский перевод (IBAN, в евро), перевод на карту Monobank в гривне или USDT в сети TRC-20. Выберите пакет в разделе «Стоимость» или напишите боту t.me/yoga15min_chat_bot — он пришлёт реквизиты и подскажет, что делать дальше.",
      "trial": "Да, до оплаты можно прийти на одну утреннюю практику и попробовать. Напишите боту в Telegram t.me/yoga15min_chat_bot — он подскажет, как присоединиться.",
      "recordings": "Записи каждой практики доступны участникам, поэтому заниматься можно и позже, в удобное время. Пропущенное утро — не проблема.",
      "beginner": "Начинать можно с нуля: практика длится 15 минут, и преподаватель ведёт её вживую. Особая гибкость, подготовка или возраст здесь не имеют значения.",
      "method": "Это подлинная йога Леди Нигумы — работа с внутренней энергией, вниманием и состоянием сознания. Это не фитнес и не тренировка.",
      "duration": "Да, 15 минут утром достаточно: здесь важна регулярность, а не длительность. А по субботам есть более длинная встреча с разбором техники.",
      "language": "Участники сообщества общаются на украинском, английском, немецком и русском. Если для вас важен конкретный язык, передам вопрос преподавателю.",
      "health": "Я не даю рекомендаций по здоровью — такие вопросы лучше обсудить лично с преподавателем. Передам ваш вопрос человеку, и вам ответят здесь, в чате.",
      "refund": "Этот вопрос решается лично — передам его человеку, и вам ответят здесь. А чтобы заранее понять, подходит ли вам практика, можно бесплатно прийти на одну утреннюю встречу до оплаты.",
      "start": "Напишите боту в Telegram t.me/yoga15min_chat_bot — он отвечает на вопросы, присылает реквизиты и напоминания. Новые группы стартуют по понедельникам.",
      "operator": "Уже передаю ваш вопрос человеку — Ольга ответит вам здесь, в этом чате. Если удобнее, можно написать в Telegram t.me/yoga15min_chat_bot или в Instagram @olga_filianova.",
      "fallback": "Кажется, вопрос мне не до конца понятен. Сформулируйте, пожалуйста, иначе — или я передам его человеку, и вам ответят здесь."
    },
    "keywords": {
      "price": [
        "цена",
        "цены",
        "сколько стоит",
        "стоимость",
        "прайс",
        "тариф",
        "тарифы",
        "абонемент",
        "подписка",
        "сколько в месяц",
        "скока стоит",
        "почем",
        "дорого",
        "стоймость"
      ],
      "schedule": [
        "расписание",
        "распесание",
        "во сколько",
        "когда занятия",
        "когда практика",
        "график",
        "по каким дням",
        "утром",
        "суббота",
        "часовой пояс",
        "если пропущу",
        "пропустил занятие",
        "во сколько начало"
      ],
      "included": [
        "что входит",
        "что включено",
        "что я получу",
        "что даёт участие",
        "что в подписке",
        "программа",
        "чат участников",
        "сообщество",
        "нетворкинг",
        "закрытый чат",
        "что получаю",
        "наполнение"
      ],
      "payment": [
        "монобанк",
        "monobank",
        "моно",
        "карта",
        "на карту",
        "usdt",
        "крипта",
        "как оплатить",
        "оплата",
        "способы оплаты",
        "реквизиты",
        "paypal",
        "пейпал",
        "криптой",
        "usdt",
        "картой",
        "банковский перевод",
        "счет на оплату"
      ],
      "trial": [
        "пробное",
        "пробное занятие",
        "бесплатно",
        "попробовать",
        "разовое",
        "прийти посмотреть",
        "первое занятие бесплатно",
        "триал",
        "без оплаты",
        "демо",
        "пробник",
        "тестовое"
      ],
      "recordings": [
        "запись",
        "записи",
        "в записи",
        "если не смогу вживую",
        "повтор",
        "видео",
        "смотреть позже",
        "не успеваю утром",
        "доступ к записям",
        "архив",
        "перезапись"
      ],
      "beginner": [
        "новичок",
        "начинающий",
        "с нуля",
        "никогда не занимался",
        "никогда не занималась",
        "не гибкий",
        "не гибкая",
        "плохая растяжка",
        "мне 50",
        "слишком стар",
        "подойдет ли мне",
        "нет опыта",
        "новечок"
      ],
      "method": [
        "что за йога",
        "нигума",
        "нигуми",
        "какая йога",
        "чем отличается",
        "методика",
        "стиль",
        "асаны",
        "внутренняя энергия",
        "медитация",
        "это фитнес",
        "духовная практика",
        "леди нигума"
      ],
      "duration": [
        "15 минут",
        "хватит ли",
        "мало времени",
        "этого достаточно",
        "почему так коротко",
        "короткая практика",
        "будет ли эффект",
        "сколько длится",
        "продолжительность",
        "длительность",
        "успею ли"
      ],
      "language": [
        "язык",
        "на каком языке",
        "по русски",
        "по-русски",
        "на русском",
        "українською",
        "english",
        "немецкий",
        "deutsch",
        "языки",
        "перевод на русский",
        "я не понимаю английский"
      ],
      "health": [
        "спина",
        "болит спина",
        "травма",
        "беременность",
        "беременна",
        "здоровье",
        "давление",
        "грыжа",
        "колени",
        "после операции",
        "противопоказания",
        "суставы",
        "можно ли мне при"
      ],
      "refund": [
        "возврат",
        "вернуть деньги",
        "если не подойдет",
        "отказаться",
        "гарантия",
        "деньги назад",
        "не понравится",
        "отменить подписку",
        "расторжение",
        "рефанд",
        "верните"
      ],
      "start": [
        "как начать",
        "как присоединиться",
        "хочу участвовать",
        "как записаться",
        "с чего начать",
        "хочу попасть",
        "когда старт",
        "новая группа",
        "регистрация",
        "вступить",
        "запись в группу",
        "хочу к вам"
      ],
      "operator": [
        "оператор",
        "человек",
        "живой человек",
        "менеджер",
        "поговорить с человеком",
        "позовите",
        "администратор",
        "связаться",
        "ольга",
        "преподаватель",
        "поговорить лично",
        "нужен человек"
      ]
    },
    "ui": {
      "title": "15minYoga",
      "subtitle": "Обычно отвечаем в течение нескольких минут",
      "placeholder": "Задайте вопрос…",
      "send": "Отправить сообщение",
      "open": "Открыть чат поддержки 15minYoga",
      "close": "Закрыть чат",
      "operatorCalled": "Передали ваш вопрос человеку — вам ответят здесь в ближайшее время.",
      "operatorJoined": "К разговору подключился человек — теперь вам отвечает Ольга.",
      "error": "Сообщение не отправилось. Попробуйте ещё раз или напишите нам в Telegram.",
      "toTelegram": "Написать в Telegram",
      "quickTitle": "Частые вопросы"
    },
    "quick": [
      "Сколько стоит",
      "Расписание",
      "Пробное занятие",
      "Я новичок"
    ]
  },
  "en": {
    "answers": {
      "greeting": "Hello, and welcome to 15minYoga. Ask me anything about the practice, the schedule or how to join — and if you'd rather speak with a person, just say so.",
      "price": "Membership is 100 € for 1 month, 500 € for 6 months and 900 € for 12 months. The longer plans simply work out cheaper per month.",
      "schedule": "Live practice runs Monday to Friday, 07:00–07:15 Vienna time (GMT+2). On Saturday there is a longer, deeper session where the technique is explained and you can ask questions. If you miss a morning, every session is recorded for members.",
      "included": "You get the daily live 15-minute practice, the longer Saturday session, recordings of everything, and the private Telegram community for members. There is also networking with other entrepreneurs and executives who practise.",
      "payment": "There are four ways to pay: PayPal, a bank transfer invoice (IBAN, in euro), a transfer to a Monobank card in hryvnia, or USDT on the TRC-20 network. Pick a plan in the “Pricing” section or write to the bot t.me/yoga15min_chat_bot — it will send you the details and walk you through it.",
      "trial": "Yes, you are welcome to join one morning session for free before you decide anything. Write to the Telegram bot t.me/yoga15min_chat_bot and we will arrange it.",
      "recordings": "Every session is recorded and members can watch whenever it suits them. So if the live morning doesn't work for you one day, nothing is lost.",
      "beginner": "Beginners are genuinely welcome — it is 15 minutes and the teacher guides you live through every step. No flexibility, sports background or particular age is needed.",
      "method": "This is the authentic yoga of Lady Niguma: it works with inner energy, attention and the state of consciousness. It is not fitness and not a workout — which is why 15 minutes is enough.",
      "duration": "Yes. The practice works with attention and inner energy rather than with muscles, so its depth does not depend on length. And 15 minutes is something you can actually keep up every morning.",
      "language": "Our community speaks Ukrainian, English, German and Russian. If you would like to know more about a particular group, I can pass you to a person.",
      "health": "I'm not able to advise on health questions, and this really is better discussed personally with the teacher. Shall I pass your question to a human? Olha will reply to you here.",
      "refund": "I'd rather not answer this from a script — such things are handled personally. Let me pass you to a person who can give you a clear answer.",
      "start": "Start with our Telegram bot t.me/yoga15min_chat_bot — it answers questions, sends payment details and reminders. New groups begin on Mondays, and you can join one morning session for free first.",
      "operator": "I've passed your question on to a person. Someone from the team will reply here shortly — you can also reach us in Telegram t.me/yoga15min_chat_bot or on Instagram @olga_filianova.",
      "fallback": "I'm not sure I understood that correctly, and I'd rather not guess. Let me pass you to a person — they will answer you right here in the chat."
    },
    "keywords": {
      "price": [
        "how much",
        "price",
        "cost",
        "pricing",
        "how much does it cost",
        "membership fee",
        "plans",
        "subscription price",
        "expensive",
        "euro",
        "monthly fee",
        "prise",
        "how much per month",
        "rates"
      ],
      "schedule": [
        "when",
        "what time",
        "schedule",
        "timetable",
        "sessions time",
        "morning time",
        "7 am",
        "saturday",
        "what if i miss",
        "which days",
        "time zone",
        "shedule",
        "vienna time",
        "weekend"
      ],
      "included": [
        "what is included",
        "included",
        "what do i get",
        "benefits",
        "membership includes",
        "community",
        "telegram group",
        "networking",
        "perks",
        "whats included",
        "what comes with it",
        "included in membership"
      ],
      "payment": [
        "monobank",
        "card",
        "card transfer",
        "usdt",
        "crypto",
        "pay",
        "payment",
        "payment methods",
        "paypal",
        "bank transfer",
        "crypto",
        "usdt",
        "card payment",
        "invoice",
        "how do i pay",
        "iban",
        "payment details",
        "paiment"
      ],
      "trial": [
        "trial",
        "free",
        "try",
        "free session",
        "try before paying",
        "test it",
        "first session free",
        "taster",
        "free class",
        "can i try",
        "trial session",
        "no cost"
      ],
      "recordings": [
        "recording",
        "recordings",
        "replay",
        "video",
        "catch up",
        "watch later",
        "missed live",
        "recorded sessions",
        "playback",
        "on demand",
        "available later",
        "can i watch it after"
      ],
      "beginner": [
        "new to yoga",
        "never done yoga",
        "complete beginner",
        "beginner",
        "newbie",
        "never done yoga",
        "not flexible",
        "too old",
        "my age",
        "no experience",
        "first time",
        "stiff",
        "out of shape",
        "am i too old",
        "begginer",
        "complete beginner",
        "beginer"
      ],
      "method": [
        "what kind of yoga",
        "niguma",
        "style",
        "type of yoga",
        "what is niguma yoga",
        "method",
        "how is it different",
        "hatha",
        "is it fitness",
        "workout",
        "tradition",
        "lineage",
        "practice style"
      ],
      "duration": [
        "15 minutes",
        "is 15 min enough",
        "how long",
        "length",
        "duration",
        "only 15",
        "short session",
        "enough time",
        "how long is the session",
        "15 mins",
        "quarter of an hour"
      ],
      "language": [
        "language",
        "what language",
        "english",
        "german",
        "ukrainian",
        "russian",
        "subtitles",
        "do you speak",
        "translation",
        "which languages",
        "spoken in",
        "languge"
      ],
      "health": [
        "back pain",
        "injury",
        "pregnant",
        "pregnancy",
        "health",
        "knee",
        "hernia",
        "blood pressure",
        "surgery",
        "medical",
        "is it safe for me",
        "contraindications",
        "doctor",
        "condition"
      ],
      "refund": [
        "refund",
        "money back",
        "cancel",
        "cancellation",
        "refunds",
        "if i dont like it",
        "stop membership",
        "unsubscribe",
        "return my money",
        "guarantee",
        "quit",
        "refudn"
      ],
      "start": [
        "how do i start",
        "join",
        "sign up",
        "how to join",
        "register",
        "get started",
        "enroll",
        "signup",
        "where do i begin",
        "subscribe",
        "when can i start",
        "new group",
        "join the group"
      ],
      "operator": [
        "human",
        "operator",
        "real person",
        "talk to someone",
        "agent",
        "support",
        "manager",
        "speak to a human",
        "teacher",
        "olha",
        "contact you",
        "live person",
        "customer service"
      ]
    },
    "ui": {
      "title": "15minYoga",
      "subtitle": "Usually replies within a few minutes",
      "placeholder": "Ask a question…",
      "send": "Send message",
      "open": "Open the 15minYoga chat",
      "close": "Close chat",
      "operatorCalled": "We've passed your question on. A person will reply here shortly.",
      "operatorJoined": "You're now talking to a person.",
      "error": "The message couldn't be sent. Please try again, or write to us in Telegram.",
      "toTelegram": "Open in Telegram",
      "quickTitle": "Popular questions"
    },
    "quick": [
      "How much is it",
      "When are sessions",
      "Try for free",
      "New to yoga"
    ]
  },
  "de": {
    "answers": {
      "greeting": "Schön, dass Sie da sind. Ich beantworte gern Ihre Fragen zu 15minYoga – zu Preisen, Zeiten oder zum Einstieg. Fragen Sie einfach.",
      "price": "Die Mitgliedschaft kostet 100 € für einen Monat, 500 € für sechs Monate und 900 € für zwölf Monate. Darin enthalten sind die täglichen Live-Praktiken, alle Aufzeichnungen und die Community.",
      "schedule": "Die Live-Praxis findet Montag bis Freitag von 07:00 bis 07:15 Uhr Wiener Zeit (GMT+2) statt. Samstags gibt es eine längere, tiefere Einheit mit Erklärung der Technik und Zeit für Fragen. Wenn Sie einmal nicht dabei sein können: Jede Einheit wird aufgezeichnet.",
      "included": "Enthalten sind die tägliche Live-Praxis, die längere Samstagseinheit sowie die Aufzeichnungen aller Sessions. Dazu kommen die private Community für Mitglieder und der Austausch mit anderen Unternehmerinnen, Unternehmern und Führungskräften, die ebenfalls praktizieren.",
      "payment": "Es gibt vier Wege zu bezahlen: PayPal, Rechnung per Banküberweisung (IBAN, in Euro), Überweisung auf eine Monobank-Karte in Hrywnja oder USDT im TRC-20-Netz. Wählen Sie ein Paket im Abschnitt „Preise“ oder schreiben Sie dem Bot t.me/yoga15min_chat_bot — er sendet Ihnen die Zahlungsdaten und begleitet Sie dabei.",
      "trial": "Ja, Sie können unverbindlich an einer Morgenpraxis teilnehmen, bevor Sie sich entscheiden. Schreiben Sie dazu einfach unserem Bot t.me/yoga15min_chat_bot.",
      "recordings": "Jede Einheit wird aufgezeichnet und steht den Mitgliedern zur Verfügung. So können Sie auch dann praktizieren, wenn Sie morgens nicht live dabei sind.",
      "beginner": "Anfängerinnen und Anfänger sind herzlich willkommen. Die Praxis dauert 15 Minuten und die Lehrerin führt Sie live durch jeden Schritt – besondere Beweglichkeit oder Vorerfahrung brauchen Sie dafür nicht.",
      "method": "Es ist die authentische Yoga-Praxis der Lady Niguma: Sie arbeitet mit der inneren Energie, der Aufmerksamkeit und dem Zustand des Bewusstseins. Es ist kein Fitness und kein Workout.",
      "duration": "15 Minuten sind bewusst gewählt – kurz genug, um sie jeden Morgen wirklich zu halten. In dieser Praxis geht es nicht um die Dauer, sondern um Aufmerksamkeit und den inneren Zustand.",
      "language": "Unsere Community spricht Ukrainisch, Englisch, Deutsch und Russisch. Wenn Sie wissen möchten, in welcher Sprache die aktuelle Gruppe praktiziert, hole ich dazu gern einen Menschen dazu.",
      "health": "Zu Gesundheit, Beschwerden oder Schwangerschaft möchte ich Ihnen hier keine Auskunft geben – das besprechen Sie am besten persönlich mit der Lehrerin Olha. Wenn Sie mögen, leite ich Ihre Frage direkt an einen Menschen weiter.",
      "refund": "Dazu kann ich Ihnen hier keine verbindliche Auskunft geben – ich leite Ihre Frage gern an einen Menschen weiter. Sie können auch zuerst kostenlos an einer Morgenpraxis teilnehmen, um in Ruhe zu schauen, ob es zu Ihnen passt.",
      "start": "Schreiben Sie unserem Bot t.me/yoga15min_chat_bot – dort bekommen Sie alle Informationen, die Zahlungsdaten und die Erinnerungen. Neue Gruppen starten immer montags.",
      "operator": "Ich habe einen Menschen dazugeholt. Olha oder jemand aus dem Team antwortet Ihnen in Kürze hier im Chat.",
      "fallback": "Das habe ich leider nicht sicher verstanden. Formulieren Sie es gern noch einmal anders – oder ich hole einen Menschen dazu, der Ihnen weiterhilft."
    },
    "keywords": {
      "price": [
        "preis",
        "preise",
        "kosten",
        "kostet",
        "wie viel",
        "wieviel",
        "was kostet das",
        "tarif",
        "tarife",
        "monatsbeitrag",
        "beitrag",
        "teuer",
        "abo",
        "jahrespreis"
      ],
      "schedule": [
        "wann",
        "uhrzeit",
        "um wie viel uhr",
        "zeiten",
        "zeitplan",
        "termine",
        "stundenplan",
        "morgens",
        "früh",
        "samstag",
        "wochenende",
        "zeitzone",
        "verpasst",
        "verpasse"
      ],
      "included": [
        "enthalten",
        "inklusive",
        "leistungen",
        "was bekomme ich",
        "was ist dabei",
        "umfang",
        "beinhaltet",
        "gruppe",
        "community",
        "networking",
        "austausch",
        "vorteile"
      ],
      "payment": [
        "monobank",
        "karte",
        "kartenüberweisung",
        "usdt",
        "krypto",
        "bezahlen",
        "bezahlung",
        "zahlung",
        "zahlungsmethoden",
        "zahlungsarten",
        "überweisung",
        "ueberweisung",
        "paypal",
        "krypto",
        "usdt",
        "iban",
        "rechnung",
        "zahlungsdaten"
      ],
      "trial": [
        "kostenlos",
        "gratis",
        "probe",
        "probestunde",
        "ausprobieren",
        "testen",
        "schnuppern",
        "unverbindlich",
        "erste stunde",
        "probetraining",
        "kennenlernen",
        "reinschnuppern"
      ],
      "recordings": [
        "aufzeichnung",
        "aufzeichnungen",
        "aufnahme",
        "aufnahmen",
        "video",
        "videos",
        "nachholen",
        "später üben",
        "spaeter ueben",
        "replay",
        "nicht live",
        "archiv"
      ],
      "beginner": [
        "anfänger",
        "anfaenger",
        "anfängerin",
        "einsteiger",
        "neuling",
        "keine erfahrung",
        "noch nie yoga",
        "nicht flexibel",
        "unbeweglich",
        "steif",
        "zu alt",
        "mein alter",
        "bin ich fit genug"
      ],
      "method": [
        "welches yoga",
        "niguma",
        "yoga art",
        "yogastil",
        "stil",
        "methode",
        "was für yoga",
        "was fuer yoga",
        "unterschied",
        "hatha",
        "meditation",
        "innere energie",
        "spirituell"
      ],
      "duration": [
        "15 minuten",
        "nur 15",
        "reicht das",
        "zu kurz",
        "dauer",
        "wie lange",
        "länge",
        "laenge",
        "genug",
        "bringt das was",
        "wirkt das",
        "kurze praxis"
      ],
      "language": [
        "sprache",
        "sprachen",
        "welche sprache",
        "in welcher sprache",
        "auf deutsch",
        "deutsch",
        "englisch",
        "russisch",
        "ukrainisch",
        "verstehe kein",
        "übersetzung",
        "uebersetzung"
      ],
      "health": [
        "rücken",
        "ruecken",
        "rückenschmerzen",
        "schmerzen",
        "schwanger",
        "schwangerschaft",
        "verletzung",
        "verletzt",
        "knie",
        "bandscheibe",
        "gesundheit",
        "krank",
        "operation",
        "beschwerden"
      ],
      "refund": [
        "rückerstattung",
        "rueckerstattung",
        "geld zurück",
        "geld zurueck",
        "erstattung",
        "kündigen",
        "kuendigen",
        "stornieren",
        "storno",
        "widerruf",
        "nicht zufrieden",
        "passt nicht",
        "aussteigen"
      ],
      "start": [
        "anmelden",
        "anmeldung",
        "beitreten",
        "mitmachen",
        "starten",
        "loslegen",
        "wie fange ich an",
        "teilnehmen",
        "registrieren",
        "einstieg",
        "telegram",
        "bot",
        "link",
        "montag"
      ],
      "operator": [
        "mensch",
        "person",
        "mitarbeiter",
        "operator",
        "berater",
        "kontakt",
        "sprechen",
        "olha",
        "lehrerin",
        "echter mensch",
        "support",
        "jemand vom team",
        "instagram",
        "hilfe"
      ]
    },
    "ui": {
      "title": "15minYoga",
      "subtitle": "Antwortet meist innerhalb weniger Minuten",
      "placeholder": "Frage stellen …",
      "send": "Nachricht senden",
      "open": "Chat öffnen",
      "close": "Chat schließen",
      "operatorCalled": "Ihre Frage ist weitergeleitet. Ein Mensch aus dem Team antwortet Ihnen in Kürze hier im Chat.",
      "operatorJoined": "Ein Mensch aus dem Team ist jetzt im Chat – Sie schreiben ab sofort direkt mit einer Person.",
      "error": "Die Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es noch einmal oder schreiben Sie uns in Telegram.",
      "toTelegram": "In Telegram öffnen",
      "quickTitle": "Häufige Fragen"
    },
    "quick": [
      "Preise und Tarife",
      "Zeiten und Termine",
      "Kostenlos ausprobieren",
      "Ich bin Anfänger"
    ]
  },
  "uk": {
    "answers": {
      "greeting": "Вітаємо у 15minYoga! Тут можна запитати про практику, розклад, участь чи оплату. Про що вам розповісти?",
      "price": "Участь коштує 100 € за місяць, 500 € за 6 місяців і 900 € за 12 місяців. Оберіть формат, який вам зручніший — решту підкажемо.",
      "schedule": "Живі практики відбуваються з понеділка по п'ятницю о 07:00–07:15 за віденським часом (GMT+2). У суботу — довша зустріч із поясненням техніки та відповідями на запитання. Якщо пропустили ранок, залишається запис.",
      "included": "Щоденні живі практики Пн–Пт, довша суботня зустріч і записи всіх занять. А ще закрита Telegram-спільнота учасників: підтримка, запитання, спільний досвід і нетворкінг з підприємцями та керівниками.",
      "payment": "Оплатити можна чотирма способами: PayPal, рахунок на банківський переказ (IBAN, у євро), переказ на картку Monobank у гривні або USDT у мережі TRC-20. Оберіть пакет у розділі «Вартість» або напишіть боту t.me/yoga15min_chat_bot — він надішле реквізити й підкаже, що робити далі.",
      "trial": "Так, можна безкоштовно приєднатися до однієї ранкової практики й спробувати. Напишіть боту t.me/yoga15min_chat_bot — він допоможе долучитися.",
      "recordings": "Записи всіх практик доступні учасникам, тож можна практикувати у зручний для вас час. Бути наживо щоранку не обов'язково.",
      "beginner": "Так, початківцям тут комфортно: практика триває 15 хвилин, і викладачка веде її наживо, крок за кроком. Особлива гнучкість чи попередній досвід не потрібні.",
      "method": "Це автентична йога Пані Нігуми — робота з внутрішньою енергією, увагою та станом свідомості. Це не фітнес і не тренування тіла.",
      "duration": "15 хвилин щоранку — це формат, який реально втримати в насиченому графіку. Тут важлива регулярність, а не тривалість.",
      "language": "У спільноті ми спілкуємося українською, англійською, німецькою та російською. Напишіть, якою мовою вам зручніше, — підкажемо деталі.",
      "health": "Питання здоров'я, травм чи вагітності ми не коментуємо в чаті — це краще обговорити особисто з викладачкою. Якщо хочете, передам ваше запитання людині, і вам відпишуть просто тут.",
      "refund": "Це питання варто обговорити особисто — умови залежать від вашої ситуації. Можу покликати людину, і вам відповідять тут, у чаті.",
      "start": "Найпростіше — написати боту в Telegram: t.me/yoga15min_chat_bot. Він розкаже деталі, надішле реквізити й нагадування. Нові групи стартують у понеділок.",
      "operator": "Уже кличу людину — вона відповість вам просто тут, у чаті. Можете тим часом описати запитання детальніше.",
      "fallback": "Перепрошую, не зовсім розумію запитання. Спробуйте сформулювати інакше — або я покличу людину, яка відповість вам тут."
    },
    "keywords": {
      "price": [
        "ціна",
        "ціни",
        "скільки коштує",
        "скільки це коштує",
        "вартість",
        "прайс",
        "тарифи",
        "почому",
        "скільки платити",
        "скільки за місяць",
        "дорого",
        "100 євро",
        "знижка",
        "сколько стоит"
      ],
      "schedule": [
        "розклад",
        "коли заняття",
        "о котрій",
        "коли практика",
        "час занять",
        "графік",
        "коли починається",
        "о 7 ранку",
        "пропустив",
        "пропустила",
        "часовий пояс",
        "субота",
        "ранкова практика",
        "росклад"
      ],
      "included": [
        "що входить",
        "що включено",
        "що я отримую",
        "входить в абонемент",
        "членство",
        "спільнота",
        "чат учасників",
        "нетворкінг",
        "що дає участь",
        "переваги",
        "що всередині",
        "склад програми"
      ],
      "payment": [
        "монобанк",
        "monobank",
        "моно",
        "картка",
        "на картку",
        "usdt",
        "крипта",
        "як оплатити",
        "оплата",
        "оплату",
        "реквізити",
        "paypal",
        "пейпал",
        "крипта",
        "usdt",
        "банківський переказ",
        "спосіб оплати",
        "як заплатити",
        "оплатити карткою"
      ],
      "trial": [
        "пробне",
        "безкоштовно",
        "спробувати",
        "пробне заняття",
        "пробний урок",
        "безкоштовна практика",
        "чи можна спробувати",
        "тріал",
        "перше заняття безкоштовне",
        "попробувати",
        "тестове"
      ],
      "recordings": [
        "запис",
        "записи",
        "відео",
        "повтор",
        "в записі",
        "чи є запис",
        "подивитися пізніше",
        "не можу наживо",
        "архів",
        "доступ до відео",
        "переглянути пізніше",
        "запись"
      ],
      "beginner": [
        "початківець",
        "новачок",
        "з нуля",
        "ніколи не займався",
        "ніколи не займалася",
        "не гнучкий",
        "не гнучка",
        "розтяжка",
        "мені 50",
        "чи не застара",
        "досвіду немає",
        "чи впораюсь",
        "підходить для початківців",
        "вік"
      ],
      "method": [
        "що за йога",
        "який стиль",
        "нігума",
        "ніґума",
        "яка практика",
        "це фітнес",
        "чим відрізняється",
        "метод",
        "техніка",
        "медитація",
        "внутрішня енергія",
        "традиція",
        "що це взагалі"
      ],
      "duration": [
        "15 хвилин",
        "чи достатньо",
        "так мало",
        "чи вистачить",
        "коротко",
        "тривалість",
        "скільки триває",
        "чи ефективно",
        "мало часу",
        "чверть години"
      ],
      "language": [
        "якою мовою",
        "мова занять",
        "українською",
        "англійською",
        "німецькою",
        "російською",
        "чи є переклад",
        "мова спілкування",
        "не розумію мови",
        "мовою"
      ],
      "health": [
        "спина",
        "болить спина",
        "травма",
        "вагітність",
        "вагітна",
        "здоров'я",
        "коліна",
        "тиск",
        "протипоказання",
        "після операції",
        "грижа",
        "шия",
        "хвороба",
        "чи можна мені"
      ],
      "refund": [
        "повернення коштів",
        "повернути гроші",
        "рефанд",
        "якщо не сподобається",
        "скасувати підписку",
        "відмовитися",
        "не підійде",
        "припинити оплату",
        "вернути гроші",
        "відмова"
      ],
      "start": [
        "як почати",
        "як приєднатися",
        "хочу приєднатися",
        "з чого почати",
        "як записатися",
        "реєстрація",
        "долучитися",
        "коли старт",
        "нова група",
        "як потрапити",
        "запишіть мене",
        "хочу спробувати практикувати"
      ],
      "operator": [
        "оператор",
        "людина",
        "жива людина",
        "з'єднайте",
        "покличте людину",
        "поговорити з людиною",
        "менеджер",
        "ольга",
        "викладачка",
        "адміністратор",
        "не бот",
        "потрібна людина",
        "підтримка"
      ]
    },
    "ui": {
      "title": "15minYoga",
      "subtitle": "Зазвичай відповідаємо за кілька хвилин",
      "placeholder": "Напишіть запитання…",
      "send": "Надіслати повідомлення",
      "open": "Відкрити чат підтримки",
      "close": "Закрити чат",
      "operatorCalled": "Ми передали ваше запитання людині — відповідь надійде сюди, у чат.",
      "operatorJoined": "До розмови приєдналася людина — тепер ви спілкуєтеся не з ботом.",
      "error": "Не вдалося надіслати повідомлення. Спробуйте ще раз або напишіть нам у Telegram.",
      "toTelegram": "Написати в Telegram",
      "quickTitle": "Популярні запитання"
    },
    "quick": [
      "Скільки коштує",
      "Розклад практик",
      "Пробне заняття",
      "Я початківець"
    ]
  }
};
